model:
  name: "UNet"
  in_channels: 3
  out_channels: 1

training:
  resume_training: True
  resume_model_path: "../saved_models/Unet_DICE_BCE/best_model.pth"  # Chemin du modèle à reprendre
  resume_checkpoint_path: "../saved_models/Unet_DICE_BCE/checkpoint.pth"
  n_epochs: 40
  learning_rate: 0.0001
  batch_size: 1
  patience: 50
  epsilon: 0.5

data:
  train_img_path: "../data/train/original/"
  train_label_path: "../data/train/ground_truth/"
  test_img_path: "../data/test/original/"
  test_label_path: "../data/test/ground_truth/"
  image_size: 512
  train_split: 0.8

paths:
  save_dir: "../saved_models/"