model:
  name: "M2Unet"
  in_channels: 3
  out_channels: 1
  model_basis: "../saved_models/m2unet/M2UNetDRIVE.pth"

training:
  resume_training: false
  resume_checkpoint_path: null
  loss : "DICE_BCE_Loss" # "BCEWithLogitsLoss"
  n_epochs: 5
  learning_rate: 0.0001
  batch_size: 1
  patience: 5
  epsilon: 0.5

prediction:
  prediction_model_path: "../saved_models/m2unet/train_20260313-142310/best_model.pth"

data:
  train_img_path: "../data/train/original/"
  train_label_path: "../data/train/ground_truth/"
  test_img_path: "../data/test/original/"
  test_label_path: "../data/test/ground_truth/"
  image_size: 2048
  train_split: 0.8

paths:
  save_dir: "../saved_models/m2unet/"

parameters:
  verbose: false